oncoscreen/urls.py
from django.contrib import admin
from django.urls import path
from bookingplatform import views
from django.contrib.auth import views as auth_views
from bookingplatform.forms import CustomSetPasswordForm
from bookingplatform.views import CustomPasswordResetView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.homepage,name='home'),
    path('about',views.aboutpage,name='about'),
    path('services',views.servicepage,name='services'),
    path('contact',views.contactpage,name='contact'),

    path('login',views.login_view,name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register',views.patient_register_view),
    path('labadmin/register/',views.labadmin_register_view,name='labadmin_register'),

    path('password_reset/',
         CustomPasswordResetView.as_view(),
         name='password_reset'
         ),
    path(
        'password_reset_done',
        auth_views.PasswordResetDoneView.as_view(
            template_name='auth/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'reset-password-confirm/<uidb64>/<token>',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='auth/password_reset_confirm.html',
            form_class = CustomSetPasswordForm
        ),
        name='password_reset_confirm'
    ),
    path(
        'reset-password-complete',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='auth/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
    path('lab/dashboard/', views.lab_dashboard, name='lab_dashboard'),
    path('patient/dashboard/', views.patient_dashboard, name='patient_dashboard'),
    path('patient/myprofile/', views.patient_profile, name='patient_profile'),
    path('patient/profile/edit/', views.patient_profile_edit, name='edit_patient_profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('booking/new/', views.book_package, name='book_any_package'),
    path('booking/new/<int:pk>/', views.book_package, name='book_any_package'),
    path('booking/<int:booking_id>/payment/', views.payment, name='payment'),
    path('booking/payment_success/<int:booking_id>/', views.payment_success, name='payment_success'),
    path('bookings/', views.my_bookings, name='my_bookings'),
    path('booking/cancel/<int:booking_id>/', views.cancel_booking, name='cancel_booking'),
    path('patient/notifications/',views.my_notifications,name='my_notifications'),
    path('patient/payments/<int:pk>/refund/', views.patient_refund_payment, name='patient_refund_payment'),

    path('all_categories_view/', views.all_categories_view, name='all_categories_view'),
    path('category_packages/<int:pk>/',views.category_packages_view,name='category_packages'),
    path('packages_detail/<int:pk>/', views.packages_detail_view, name='packages_detail'),

    path('lab/dashboard/create_package/', views.create_package, name='create_package'),
    path('lab/lab_view_package/', views.lab_packages_list_view, name='lab_view_package'),
    path('lab/lab_package_details/<int:pk>/', views.lab_packages_edit, name='lab_package_details'),
    path('lab/lab_package_delete/<int:package_id>/', views.lab_packages_delete, name='lab_package_delete'),
    path('lab/tests/', views.lab_test_list, name='lab_test_list'),
    path('lab/tests/add/', views.lab_test_create, name='lab_test_create'),
    path('lab/tests/edit/<int:pk>/', views.lab_test_edit, name='lab_test_edit'),
    path('lab/tests/<int:pk>/', views.lab_test_delete, name='lab_test_delete'),
    path('lab/dashboard/staff_register/',views.create_staff_view,name='staff_register'),
    path('lab/staff_view_list/',views.staff_view_list,name='staff_view_list'),
    path('lab/staff_edit/<int:pk>/',views.staff_edit,name='staff_edit'),
    path('lab/staff_delete/<int:pk>/', views.staff_delete, name='staff_delete'),
    path('staff/dashboard/', views.staff_dashboard, name='staff_dashboard'),
    path('lab/bookings/', views.lab_booking_list, name='lab_booking_list'),
    path('bookings/mark_sample_collected/<int:pk>/', views.mark_sample_collected, name='mark_sample_collected'),
    path('slots/', views.slot_list, name='slot_list'),
    path('slots/create/', views.create_slot, name='create_slot'),
    path('slots/edit/<int:pk>/', views.edit_slot, name='edit_slot'),
    path('lab/slot/<int:pk>/', views.delete_or_disable_slot, name='delete_or_disable_slot'),
    path('lab/bookings/<int:pk>/upload-report/',views.upload_test_report,name='upload_test_report'),
    path('lab/bookings/<int:pk>/complete/',views.mark_booking_completed,name='mark_booking_completed'),
    path('lab/payments/', views.lab_payment_list, name='lab_payment_list'),
    path('lab/payments/<int:pk>/refund/', views.refund_payment, name='refund_payment'),
    # path("payments/export/", views.export_payments_csv, name="export_payments"),

    path('search_package_list', views.search_package_list, name='search_package_list'),


]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

bookingplatform/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from ckeditor.fields import RichTextField
from django.core.exceptions import ValidationError
from django.utils.timezone import now
from django.utils import timezone
from datetime import timedelta


#--------------------------------------#
# Custom User model
#--------------------------------------#

class User(AbstractUser):
    ROLE_CHOICES = (
        ('PATIENT', 'Patient'),
        ('LAB_ADMIN', 'Lab Admin'),
        ('STAFF', 'Staff'),
    )

    role = models.CharField(
        max_length=20,
        choices=ROLE_CHOICES,
        default='PATIENT'
    )

    def __str__(self):
        return self.username or self.email

#--------------------------------------#
# Patient Profile model
#--------------------------------------#

class PatientProfile(models.Model):
    GENDER_CHOICES = (
        ('MALE','Male'),
        ('FEMALE','Female'),
    )

    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name='patient_profile'
    )
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    dob = models.DateField(null=True, blank=True)
    mobile = models.CharField(max_length=13)

    gender = models.CharField(
        max_length=10,
        choices=GENDER_CHOICES,
        null=True,
        blank=True
    )
    address = models.TextField(
        null=True,
        blank=True
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

#--------------------------------------#
# Lab Profile model
#--------------------------------------#

class Lab(models.Model):
    name = models.CharField(max_length=255)
    mobile = models.CharField(max_length=15)
    address = models.TextField(blank=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name
    
#--------------------------------------#
# Lab Admin Profile model
#--------------------------------------#

class LabAdminProfile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name='labadmin_profile'
    )
    lab = models.ForeignKey(
        Lab,
        on_delete=models.CASCADE,
        related_name='lab_admins'
    )
    name = models.CharField(max_length=100, blank=True)
    mobile = models.CharField(max_length=10, blank=True)

    def __str__(self):
        return self.user.email    
#--------------------------------------#
# Package Category model
#--------------------------------------#
class PackageCategory(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    icon = models.CharField(
        max_length=255,
        help_text='Font Awesome icons(e.g. fa-dna, fa-heartbeat)',
        blank=True
    )

    def __str__(self):
        return self.name

#--------------------------------------#
# Lab Package model
# one lab-one package
#--------------------------------------#

class LabTest(models.Model):
    RESULT_TYPE_CHOICES = (
        ('NUMERIC','Numeric'),
        ('BINARY','Positive / Negative'),
        ('TEXT','Text'),
        ('IMAGING', 'Imaging /Scan'),
    )

    name = models.CharField(max_length=255,unique=True)
    description = models.TextField()

    result_type = models.CharField(
        max_length=20,
        choices=RESULT_TYPE_CHOICES
    )
    created_at = models.DateTimeField(auto_now_add=True)


    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        self.name = self.name.strip()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name
    
    class Meta:
        
        ordering = ['-name']

class LabPackage(models.Model): #labprofile is deleted will delete all packages
    HOME_COLLECTION_CHOICES = (
        ('YES', 'Home Collection Available'),
        ('NO', 'Lab Visit Required'),
        )
    #one lab has many packages
    lab = models.ForeignKey(
        Lab,
        on_delete=models.CASCADE,
        related_name='packages'
    )


    category = models.ForeignKey(
        PackageCategory,
        on_delete=models.SET_NULL,
        null=True,
        related_name='packages'
    )

    name = models.CharField(max_length=255)
    intro_heading = models.CharField(
        max_length=255,
         help_text="Eg: What is Breast Cancer?"
         )
    intro_description = RichTextField()
    tests = models.ManyToManyField(
        LabTest,
        related_name='packages',
        blank=True
    )
    risk_factors = RichTextField()
    age_recommendation = RichTextField()
    min_age = models.PositiveBigIntegerField(
        null=True,
        blank=True,
        help_text='Minimum age in years'
    )
    max_age = models.PositiveBigIntegerField(
        null=True,
        blank=True,
        help_text='Maximum age in years'
    )
    gender = models.CharField(
        max_length=10,
        choices=(
            ('MALE','Male'),
            ('FEMALE','Female'),
            ('BOTH','Both'))        
    )
    recommended_age_text = models.CharField(max_length=255,null=True,blank=True)
    price = models.DecimalField(max_digits=8,decimal_places=2)
    report_time = models.CharField(max_length=100)
    home_collection = models.CharField(
        max_length=3,
        choices=HOME_COLLECTION_CHOICES,
        default='NO'
        )
    is_active = models.BooleanField(default=True)
    created_at=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    


#--------------------------------------#
# Staff model
#--------------------------------------#

class StaffProfile(models.Model):
    DESIGNATION_CHOICES = (
        ('TECH', 'Lab Technician'),
        ('PHLEB', 'Phlebotomist'),
        ('RECEP', 'Receptionist'),
        ('COUNS', 'Counselor'),
        ('OTHER', 'Other'),
    )
    
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name='staffprofile'
        )
    lab = models.ForeignKey(
        Lab,
        on_delete=models.CASCADE
        )
    staff_id = models.CharField(max_length=255,unique=True)
    full_name = models.CharField(max_length=255)
    mobile = models.CharField(max_length=15)
    designation = models.CharField(
        max_length=10,
        choices=DESIGNATION_CHOICES,
        blank=True,
        null=True
    )
    other_designation = models.CharField(max_length=50, blank=True)

    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.staff_id} -{self.full_name}'
    
class BookingSlot(models.Model):

    COLLECTION_CHOICES = (
        ('LAB', 'Lab Visit'),
        ('HOME', 'Home Collection'),
    )

    RESOURCE_TYPE_CHOICES = (
        ('EXCLUSIVE', 'Exclusive Resource'),  # scan / machine
        ('SHARED', 'Shared Resource'),        # blood collection,etc
    )

    SLOT_CHOICES = (
        ('10-11', '10:00 AM - 11:00 AM'),
        ('11-12', '11:00 AM - 12:00 PM'),
        ('13-14', '1:00 PM - 2:00 PM'),
        ('14-15', '2:00 PM - 3:00 PM'),
    )

    date = models.DateField()
    time_slot = models.CharField(max_length=10, choices=SLOT_CHOICES)

    collection_type = models.CharField(
        max_length=10,
        choices=COLLECTION_CHOICES
    )

    resource_type = models.CharField(
        max_length=10,
        choices=RESOURCE_TYPE_CHOICES
    )

    max_bookings = models.PositiveIntegerField(default=1)
    booked_count = models.PositiveIntegerField(default=0)

    is_active = models.BooleanField(default=True)

    def is_available(self):
        return self.booked_count < self.max_bookings
    
    def __str__(self):
        return f'{self.get_time_slot_display()} -  {self.collection_type}'
    
    #avoid duplicate slot lab-shared slots for same time
    class Meta:
        unique_together = (
            'date',
            'time_slot',
            'collection_type',
            'resource_type',
        )
        ordering = ['-date', '-time_slot']

class Booking(models.Model):

    slot =models.ForeignKey(
        BookingSlot,
        on_delete=models.PROTECT, #Slot should not be deleted if bookings exist
        null=True,
        blank=True,
        related_name='bookings'
    )
    
    STATUS_CHOICES = (
        ('PENDING','Pending'),
        ('CONFIRMED','Confirmed'),
        ('SAMPLE COLLECTED','Sample Collected'),
        ('REPORT UPLOADED', 'Report Uploaded'),
        ('COMPLETED','Completed'),
        ('CANCELLED','Cancelled'),
        ('EXPIRED', 'Expired'),
    )

    COLLECTION_CHOICES = (
        ('HOME','Home Collection'),
        ('LAB','Lab Visit'),
    )

    PAYMENT_STATUS_CHOICES = (
        ('PENDING','Pending'),
        ('SUCCESS','Success'),
        ('REFUNDED', 'Refunded'),
        ('FAILED','Failed'),
    )

    #Relations

    #if user delete booking deleted
    patient = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete = models.CASCADE,
        related_name = 'bookings'
    )

    #
    package = models.ForeignKey(
        LabPackage,
        on_delete=models.PROTECT, #safeyt feature to preven deleting a package if booking attached to it
        related_name='bookings'
    )

    #appointment detaisl

    preferred_date = models.DateField()

    collection_type = models.CharField(
        max_length=10,
        choices=COLLECTION_CHOICES,
        default='LAB'
    )
    amount = models.PositiveIntegerField(default=0)

    #BOOKING LIFECYCLE
    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default='PENDING'
    )

    #MOCK PAYMENT
    payment_status = models.CharField(
        max_length=10,
        choices=PAYMENT_STATUS_CHOICES,
        default='PENDING'
    )

    #Optional notes
    notes = models.TextField(

templates/dashboard/patients/book_package.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <!-- Book Package Page -->
    <div class="page-title" data-aos="fade">
      <nav class="breadcrumbs">
        <div class="container">
          <ol>
            <li><a href="/">Home</a></li>
            <li class="current">Book Package</li>
          </ol>
        </div>
      </nav>
    </div><!-- End Book Package Page -->



    <!-- Book Package Section -->
   <section id="contact" class="contact section">

      <!-- Section Title -->
      <div class="container section-title" data-aos="fade-up">
        <h2>Book Package</h2>
      </div><!-- End Section Title -->

      <div class="container">
        {% if messages %}
            {% for message in messages %}
            <div class="alert {% if message.tags == 'success' %}alert-success{% else %}alert-danger{% endif %} alert-dismissible fade show" role="alert">{{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}               
        {% endif %}

        <div class="row gy-2  justify-content-center">

          <div class="col-lg-8" data-aos="fade-up" data-aos-delay="100">
            <form  method="POST" role="form" class="php-email-form" >
                
                {% csrf_token %}
              <div class="row">               
                    <div class="col">
                     
                        <label for="package" class="form-label text-secondary">Package</label>
                        <!-- <select id="id_package" name="package" class="form-select" {% if package_locked %} disabled {% endif %}>
                           <option value="">-- Select Package --</option> -->
                          <!-- from the booking form select only active-true test packages -->
                          <!-- {% for pkg in form.fields.package.queryset %}
                          <option value="{{pkg.id}}" {% if package and pkg.id == package.id  %} selected {% endif %}  data-home="{{pkg.home_collection}}">{{pkg.name}}</option>
                          {% endfor %}
                          </select> -->
                          {% if package_locked %}
                          <input type="hidden" name="package" value="{{package.id}}">
                          {% endif %}
                          {{ form.package }}
                    </div>
                    <div class="col">
                        <label for="preferreddate" class="form-label text-secondary">Date</label>
                        {{ form.preferred_date }}
                        
                    </div>
                </div>
                <div class="row mt-3">               
                    <div class="col">
                        <label for="preferreddate" class="form-label text-secondary">Collection Type</label>
                        <div id="collection-wrapper">{{ form.collection_type }}</div>
                        
                        <small id="text-muted">
                         Home collection is not available for this package
                        </small>
                       
                        
                    </div>
                    <div class="slot-container col" id="slot-container">
                      
                      {% if form.no_slots_available %}
                        <p class="text-danger">
                          No slots available for the selected date
                        </p>
                        {% else %}
                          {% for radio in form.slot %}
                            <label class="slot-btn">
                                {{ radio.tag }}
                                <span>{{ radio.choice_label }}</span>
                            </label>
                          {% endfor %}

                      {% endif %}
                    </div>
                </div>
                <button type="submit" name="check_slots" class="btn btn-outline-primary">
                    Check Slot Availability
                </button>

    
              <div class="mt-3">
                <div class="text-center"><button type="submit" >Book Test</button></div>
              </div>
            </form>
          </div><!-- End Book Package -->



        </div>

      </div>

    </section><!-- /Book Package Section -->
   

{% endblock %} 

templates/dashboard/patients/booking_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <!-- Booking Detail Page -->
    <div class="page-title" data-aos="fade">
      <nav class="breadcrumbs">
        <div class="container">
          <ol>
            <li><a href="/">Home</a></li>
            <li class="current">Booking List</li>
          </ol>
        </div>
      </nav>    <!-- Booking Section -->

      <!-- View Booking Section -->
    <section id="contact" class="contact section">

      <!-- Section Title -->
      <div class="container section-title" data-aos="fade-up">
        <h2>My Bookings</h2>
      </div><!-- End Section Title -->



      <div class="container" data-aos="fade-up" data-aos-delay="100">
        {% if messages %}
            {% for message in messages %}
            <div class="alert {% if message.tags == 'success' %}alert-success{% else %}alert-danger{% endif %} alert-dismissible fade show" role="alert">{{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}               
        {% endif %}

          <div class="row justify-content-center g-0">
              <div class="col-lg-12 col-md-10 col-12 p-0 view_table border rounded-3 overflow-hidden">
                    <table class="table table-success table-striped table-hover mb-0" >
                        <thead class="text-white" >
                            <tr class="">
                            <th scope="col" class="border-0 thead">#</th>
                            <th scope="col" class="border-0 thead">Package</th>
                            <th scope="col" class="border-0 thead">Test Date</th>
                            <th scope="col" class="border-0 thead">Slot</th>
                            <th scope="col" class="border-0 thead">Status</th>
                            <th scope="col" class="border-0 thead">Reports</th>
                            <th scope="col" class="border-0 thead">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for booking in bookings %}
                                <tr>
                                <th scope="row">{{ bookings.start_index|add:forloop.counter0 }}</th>
                                <td>{{booking.package.name}}</td>
                                <td>{{booking.preferred_date}}</td>
                                <td>{% if booking.slot %}
                                    <!-- show 10-11 as 10AM -11AM -->
                                        {{ booking.slot.get_time_slot_display }}
                                    {% else %}
                                        —
                                    {% endif %}
                                </td>
                                <td>
                                  
                                  {% if booking.status == 'PENDING' and booking.preferred_date >= today %}
                                    <a href="{% url 'payment' booking.id %}" class="btn btn-warning">Pay Now</a>
                                  {% elif  booking.status == 'EXPIRED' %}
                                    <span class="badge bg-danger">Expired</span>
                                     {% else %}
                                    <span class="badge bg-{% if booking.status == 'CONFIRMED' %}success {% else %}secondary{% endif %}">{{booking.status }}</span>
                                  {% endif %}
                                </td>
                                <td>
                                  {% if booking.status == 'CONFIRMED'  %}
                                  <span class="badge bg-secondary "><i class="fa-solid fa-hourglass-half"></i> Sample Collection Pending</span>
                                  {% elif booking.status in 'REPORT UPLOADED COMPLETED' %}
                                  <a href="{{ booking.report.file.url }}" target="_blank" class="btn  btn-success "><i class="fa-solid fa-download"></i> Download Report</a>
                                  {% elif booking.status == 'SAMPLE COLLECTED' %}
                                  <span class="badge bg-primary "><i class="fa-solid fa-hourglass-half"></i> Report will be uploaded soon</span>
                                  {% else %}
                                    —
                                  {% endif %}
                                </td>
                                <td >       
                                    {% if booking.can_cancel  %}
                                        <button  title="{{booking.id}}"
                                        data-bs-toggle="modal" 
                                        data-bs-target="#confirmcancel{{ booking.id }}"
                                        class="btn btn-danger btn-sm">
                                        Cancel
                                      </button>
                                    {% else %}
                                        <span class="text-muted small">Cancellation closed</span>
                                    {% endif %}  
                                    <!-- {{booking.expires_at}}                        -->
                                    
                                    
                                </td>
                                </tr>
                             {% endfor %}
                        </tbody>
                    </table>

              </div>
              <!--End Bookings List-->
                    <nav aria-label="Bookingnavigation" class="mt-3 bg-white ">
                        <ul class="pagination justify-content-center mb-0">
                            <li class="page-item {% if not bookings.has_previous %}disabled{% endif %}">
                                <a class="page-link" href="{% if bookings.has_previous %}?page={{ bookings.previous_page_number }}{% else %}#{% endif %}">Previous</a>
                            </li>
                            {% for num in bookings.paginator.page_range %}
                            <li class="page-item {% if num == bookings.number %}active{% endif %}" {% if num == bookings.number %}aria-current="page"{% endif %}>
                                <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                            </li>
                            {% endfor %}
                            
                            <li class="page-item {% if not bookings.has_next %}disabled{% endif %}">
                                <a class="page-link" href="{% if bookings.has_next %}?page={{ bookings.next_page_number }}{% else %}#{% endif %}">Next</a>
                            </li>
                           
                        </ul>
                    </nav>
          </div>


        </div>

      </div>

    </section><!-- /Bookings Section -->
   <!-- Cancel Confirmation Modal -->
<!-- Button trigger modal -->


<!-- Modal -->
  {% for booking in bookings %}
<div class="modal fade" id="confirmcancel{{ booking.id }}" tabindex="-1" aria-labelledby="confirmcancelLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="confirmcancelLabel">Cancel Booking</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure you want to cancel this booking?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
        <form method="post" action="{% url 'cancel_booking' booking.id  %}"  id="cancelForm">
            {% csrf_token %}
            <button type="submit" title="{% url 'cancel_booking' booking.id  %}" class="btn btn-danger">Yes, Cancel</button>

        </form>
      </div>
    </div>
  </div>
</div>
{% endfor %}


{% endblock %} 

templates/dashboard/patients/change_passowrd.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <!-- Profile Page -->
    <div class="page-title" data-aos="fade">
      <nav class="breadcrumbs">
        <div class="container">
          <ol>
            <li><a href="/">Home</a></li>
            <li class="current">Change Password</li>
          </ol>
        </div>
      </nav>
    </div><!-- End Profile Page -->



    <!-- Profile Section -->
   <section id="contact" class="contact section">

      <!-- Section Title -->
      <div class="container section-title" data-aos="fade-up">
        <h2>Change Pasword</h2>
      </div><!-- End Section Title -->

      <div class="container">

        <div class="row gy-2  justify-content-center">

          <div class="col-lg-8" data-aos="fade-up" data-aos-delay="100">
            {% if not request.user.patient_profile.gender or not request.user.patient_profile.address %}
              <div class="alert alert-warning">
                Please complete your profile to proceed with booking.
              </div>
            {% endif %}
            <form  method="POST" role="form" class="php-email-form" >
                
                {% csrf_token %}
              <div class="row">               
                    <div class="col">
                        <label for="loginusername" class="form-label text-secondary">First Name</label>
                        {{ form.first_name }}
                    </div>
                    <div class="col">
                        <label for="loginusername" class="form-label text-secondary">Last Name</label>
                        {{ form.last_name }}
                        
                    </div>
                </div>
                <div class="row mt-3"> 
                    <div class="col">
                        <label for="loginusername" class="form-label text-secondary">Date of Birth</label>
                         {{ form.dob }}
                    </div>
                    <div class="col">
                        <label for="loginusername" class="form-label text-secondary">Mobile</label>
                         {{ form.mobile }}
                         <small class="text-danger">
                            {{ form.mobile.errors }}
                         </small>
                        
                    </div>
                </div>
                <div class="row mt-3"> 
                    <div class="col-md-4">
                        <label for="loginusername" class="form-label text-secondary">Gender</label>
                         {% for radio in form.gender %}
                            <div class="form-check">
                                {{ radio.tag }}
                                <label class="form-check-label">
                                    {{ radio.choice_label }}
                                </label>
                            </div>
                        {% endfor %}
                    </div>
                    <div class="col-md-4">
                        <label for="loginusername" class="form-label text-secondary">Address</label>
                         {{form.address}}
                    </div>
                  
                   
                </div>

    
              <div class="mt-3">
                <div class="text-center"><button type="submit">Update Profile</button></div>
              </div>
            </form>
          </div><!-- End Profile -->



        </div>

      </div>

    </section><!-- /Doctors Section -->
   

{% endblock %} 